version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
  
  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - "9412:9411"