version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.14
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9412:9411"